# Generated by Django 5.2.17 on 2026-09-04 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('servicio', models.CharField(blank=True, choices=[('', 'Selecciona un servicio...'), ('masaje-descontracturante', 'Masaje Descontracturante'), ('masaje-relajante', 'Masaje Relajante'), ('masaje-terapeutico', 'Masaje Terapéutico'), ('masaje-piedras', 'Masaje con Piedras Calientes'), ('corte', 'Corte y Peinado'), ('coloracion', 'Coloración'), ('tratamiento', 'Tratamientos Capilares'), ('alisado', 'Alisados'), ('recogido', 'Recogidos y Bodas'), ('infantil', 'Peluquería Infantil'), ('otros', 'Otros')], max_length=50, verbose_name='Servicio de interés')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
