# Generated by Django 5.2.17 on 2026-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
    ]
