# Generated by Django 5.2.17 on 2026-09-09 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_mensajecontacto_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('espacio', 'Nuestro Espacio'), ('masajes', 'Masajes'), ('peluqueria', 'Peluquería')], max_length=20, verbose_name='Categoría')),
                ('orden', models.IntegerField(default=0, help_text='Menor número = aparece antes', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('masaje', 'Masaje'), ('peluqueria', 'Peluquería')], max_length=20, verbose_name='Categoría')),
                ('duracion', models.CharField(blank=True, help_text='Ej: 60-90 min', max_length=50, verbose_name='Duración')),
                ('tecnica', models.CharField(blank=True, help_text='Ej: Presión profunda', max_length=100, verbose_name='Técnica')),
                ('beneficio', models.CharField(blank=True, help_text='Ej: Alivio del dolor muscular', max_length=100, verbose_name='Beneficio')),
                ('orden', models.IntegerField(default=0, help_text='Menor número = aparece antes', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
